import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  //  name : 'Trinity',
      //  listViewurl :'https://plymouth.beyondexs.com/api/wslistview_mysql.php',
     loginUrl:'http://10.80.129.181:81/api/Login',
    //  authUrl:'https://plymouth.beyondexs.com/api/auth.php',
    //  comboUrl:'https://plymouth.beyondexs.com/api/APIController.php',
    //  apiUrl :'https://plymouth.beyondexs.com/api/APIController.php',
    //  imgUploadUrl:'https://plymouth.beyondexs.com/imgup.php',
    //  imageUrl:'https://plymouth.beyondexs.com/uploads/images/',
    //  imageNameUpdateUrl:'https://plymouth.beyondexs.com/api/CMController.php',
    //  attachmentUrl:'https://plymouth.beyondexs.com/uploads/attachments/',
    //  custprodattachmentUrl:'https://plymouth.beyondexs.com/uploads/custimage/',
    //  fileUploadUrl:'https://plymouth.beyondexs.com/fileupload.php',
    //  csvUploadUrl:'https://plymouth.beyondexs.com/api/csvupload.php',
    //  pcdurl:'https://plymouth.beyondexs.com/api/PCDController.php',
    //  pdfurl:'https://plymouth.beyondexs.com/tcpdf/',
    //  indentUrl:'https://plymouth.beyondexs.com/api/IndentController.php',
    //  invoiceUrl:'https://plymouth.beyondexs.com/api/InvoiceController.php',
    //  commonUrl : 'https://plymouth.beyondexs.com/api/CommonController.php',
    //  bomCopyUrl: 'https://plymouth.beyondexs.com/api/VersioningController.php',
    //  bomHeaderUrl: 'https://plymouth.beyondexs.com/api/BOMController.php',
    //  stockUrl:'https://plymouth.beyondexs.com/api/StockController.php',
    //  batchUrl:'https://plymouth.beyondexs.com/api/BatchstructureController.php',
    //  finalinvUrl:'https://plymouth.beyondexs.com/api/FinalInvoiceController.php',
    //  proformainvUrl:'https://plymouth.beyondexs.com/api/ProfoinvoiceController.php',
    //  orderUrl:'https://plymouth.beyondexs.com/api/CustomerOrder.php',
    //  stockReqUrl:'https://plymouth.beyondexs.com/api/StockRequirement.php',
    //  productUrl:'https://plymouth.beyondexs.com/api/StockProcedure.php',
    //  bomLkUrl:'https://plymouth.beyondexs.com/api/InvoiceBomLkController.php',
    //  designPUrl:'https://plymouth.beyondexs.com/api/UomconversiongetController.php',
    //  costingMatrialUrl:'https://plymouth.beyondexs.com/api/BomcostController.php?',
    //  conversionUrl:'https://plymouth.beyondexs.com/api/UomconversiongetController.php',
    //  userGroupUrl:'https://plymouth.beyondexs.com/api/GroupaccessController.php',
    //  dcTrackingUrl:'https://plymouth.beyondexs.com/api/DctrackingController.php',
    //  trackingUrl:'https://plymouth.beyondexs.com/api/MaterialtrackingController.php',
    //  supplierTrackUrl:'https://plymouth.beyondexs.com/api/SuppliertrackingController.php',
    //  materialsTrackingUrl:'https://plymouth.beyondexs.com/api/MaterialTrackingChart.php',
    //  supplytrackingUrl:'https://plymouth.beyondexs.com/api/SupplierTrackingChart.php',
    //  producttrackingUrl:'https://plymouth.beyondexs.com/api/ProductpriceController.php?',
    //  pIndentUrl:'https://plymouth.beyondexs.com/api/PurchaseIndentController.php',
    //  prdCardBthUrl:'https://plymouth.beyondexs.com/api/PrdBatchIssueController.php',
    //  customerorderanalysisUrl:'https://plymouth.beyondexs.com/api/CustomerOrderChart.php?',
    //  prductorderanalysisUrl:'https://plymouth.beyondexs.com/api/ProductOrderChart.php?',
    //  mailContentGeturl:'https://plymouth.beyondexs.com/api/EmailController.php',
    //  mailSendUrl:'https://plymouth.beyondexs.com/api/invoicemail.php',
    //  materialUomCovUrl:'https://plymouth.beyondexs.com/api/MaterialUOMConversionController.php',
    //  decryptUrl:'https://plymouth.beyondexs.com/api/HashtokenController.php',
    //  costingLeatherUrl:'https://plymouth.beyondexs.com/api/BomLeathercost.php',
    //  customerLeatherUrl:'https://plymouth.beyondexs.com/api/CustomerLeatherController.php',
    //  dcsummaryUrl:'https://plymouth.beyondexs.com/api/getdcsummary.php',
    //  dcpostsummaryUrl:'https://plymouth.beyondexs.com/api/postdcsummary.php',
    //  getempdeploymentUrl:'https://plymouth.beyondexs.com/api/getempdeployment.php?',
    //  postempdeployment:'https://plymouth.beyondexs.com/api/postempdeployment.php?',
    //  matProcurementUrl:'https://plymouth.beyondexs.com/api/MaterialProcurementChart.php',
    //  stockorderUrl:'https://plymouth.beyondexs.com/api/MaterialOrderReportController.php',
    //  alterNateMaterial:'https://plymouth.beyondexs.com/api/AlterMaterialController.php',
    //  Send2mailUrl:'https://plymouth.beyondexs.com/Mail/MailPriceBook.php',
    //  EncryptionUrl:"https://plymouth.beyondexs.com/api/encryption.php?",
    //EditAddTruck 
     LookupUrl:"http://10.80.129.181:81/api/Company",
     driverUrl:"http://10.80.129.181:81/api/Driver",
     truckUrl:"http://10.80.129.181:81/api/Truck",
     doorUrl:"  http://10.80.129.181:81/api/Door",
     editaddTruckUrl:"http://10.80.129.181:81/api/PostTruckHeader",
     truckdetailUrl:"https://lapi.beyondexs.com/api/TruckDetail/post",
     truckdetailListUrl:"http://10.80.129.181:81/api/ListView/ListView",
    //  http://10.80.129.181:81/api/ListView/ListView 
     truckdetailUpdateUrl: "https://lapi.beyondexs.com/api/TruckDetail/update/",
companyListViewUrl:"https://lapi.beyondexs.com/api/company/ListView",
routeListViewUrl:"https://lapi.beyondexs.com/api/route/ListView",
truckListViewUrl:"https://lapi.beyondexs.com/api/truck/ListView",
driverListViewUrl:"https://lapi.beyondexs.com/api/driver/ListView",
     RouteUrl:"http://10.80.129.181:81/api/Route",
     EnquirylistUrl:"http://10.80.129.181:81/api/EnquiryListView",
    truckPostUrl:" https://lapi.beyondexs.com/api/truck/post",
          driverPostUrl:" https://lapi.beyondexs.com/api/driver/post",
        driverdeleteUrl:" https://lapi.beyondexs.com/api/driver/delete",
             truckdeleteUrl:" https://lapi.beyondexs.com/api/truck/delete",
           
// CompanyPostUrl:" https://lapi.beyondexs.com/api/company/post",
    //   RoutePostUrl:" https://lapi.beyondexs.com/api/route/post",
      // companydeleteUrl:" https://lapi.beyondexs.com/api/company/delete",
          //  routedeleteUrl:" https://lapi.beyondexs.com/api/route/delete",
    //  listViewurl :'https://ppb.beyondexs.com/api/wslistview_mysql.php',
    //  loginUrl:'https://ppb.beyondexs.com/api/LController.php',
    //  authUrl:'https://ppb.beyondexs.com/api/auth.php',
    //  comboUrl:'https://ppb.beyondexs.com/api/APIController.php',
    //  apiUrl :'https://ppb.beyondexs.com/api/APIController.php',
    //  imgUploadUrl:'https://plymouth.beyondexs.com/imgup.php',
    //  imageUrl:'https://ppb.beyondexs.com/uploads/images/',
    //  imageNameUpdateUrl:'https://ppb.beyondexs.com/api/CMController.php',
    //  attachmentUrl:'https://plymouth.beyondexs.com/uploads/attachments/',
    //  custprodattachmentUrl:'https://plymouth.beyondexs.com/uploads/custimage/',
    //  fileUploadUrl:'https://plymouth.beyondexs.com/fileupload.php',
    //  csvUploadUrl:'https://ppb.beyondexs.com/api/csvupload.php',
    //  pcdurl:'https://ppb.beyondexs.com/api/PCDController.php',
    //  pdfurl:'https://plymouth.beyondexs.com/tcpdf/',
    //  indentUrl:'https://ppb.beyondexs.com/api/IndentController.php',
    //  invoiceUrl:'https://ppb.beyondexs.com/api/InvoiceController.php',
    //  commonUrl : 'https://ppb.beyondexs.com/api/CommonController.php',
    //  bomCopyUrl: 'https://ppb.beyondexs.com/api/VersioningController.php',
    //  bomHeaderUrl: 'https://ppb.beyondexs.com/api/BOMController.php',
    //  stockUrl:'https://ppb.beyondexs.com/api/StockController.php',
    //  batchUrl:'https://ppb.beyondexs.com/api/BatchstructureController.php',
    //  finalinvUrl:'https://ppb.beyondexs.com/api/FinalInvoiceController.php',
    //  proformainvUrl:'https://ppb.beyondexs.com/api/ProfoinvoiceController.php',
    //  orderUrl:'https://ppb.beyondexs.com/api/CustomerOrder.php',
    //  stockReqUrl:'https://ppb.beyondexs.com/api/StockRequirement.php',
    //  productUrl:'https://ppb.beyondexs.com/api/StockProcedure.php',
    //  bomLkUrl:'https://ppb.beyondexs.com/api/InvoiceBomLkController.php',
    //  designPUrl:'https://ppb.beyondexs.com/api/UomconversiongetController.php',
    //  costingMatrialUrl:'https://ppb.beyondexs.com/api/BomcostController.php?',
    //  conversionUrl:'https://ppb.beyondexs.com/api/UomconversiongetController.php',
    //  userGroupUrl:'https://ppb.beyondexs.com/api/GroupaccessController.php',
    //  dcTrackingUrl:'https://ppb.beyondexs.com/api/DctrackingController.php',
    //  trackingUrl:'https://ppb.beyondexs.com/api/MaterialtrackingController.php',
    //  supplierTrackUrl:'https://ppb.beyondexs.com/api/SuppliertrackingController.php',
    //  materialsTrackingUrl:'https://ppb.beyondexs.com/api/MaterialTrackingChart.php',
    //  supplytrackingUrl:'https://ppb.beyondexs.com/api/SupplierTrackingChart.php',
    //  producttrackingUrl:'https://ppb.beyondexs.com/api/ProductpriceController.php?',
    //  pIndentUrl:'https://ppb.beyondexs.com/api/PurchaseIndentController.php',
    //  prdCardBthUrl:'https://ppb.beyondexs.com/api/PrdBatchIssueController.php',
    //  customerorderanalysisUrl:'https://ppb.beyondexs.com/api/CustomerOrderChart.php?',
    //  prductorderanalysisUrl:'https://ppb.beyondexs.com/api/ProductOrderChart.php?',
    //  mailContentGeturl:'https://ppb.beyondexs.com/api/EmailController.php',
    //  mailSendUrl:'https://ppb.beyondexs.com/api/invoicemail.php',
    //  materialUomCovUrl:'https://ppb.beyondexs.com/api/MaterialUOMConversionController.php',
    //  decryptUrl:'https://ppb.beyondexs.com/api/HashtokenController.php',
    //  costingLeatherUrl:'https://ppb.beyondexs.com/api/BomLeathercost.php',
    //  customerLeatherUrl:'https://ppb.beyondexs.com/api/CustomerLeatherController.php',
    //  dcsummaryUrl:'https://ppb.beyondexs.com/api/getdcsummary.php',
    //  dcpostsummaryUrl:'https://ppb.beyondexs.com/api/postdcsummary.php',
    //  getempdeploymentUrl:'https://ppb.beyondexs.com/api/getempdeployment.php?',
    //  postempdeployment:'https://ppb.beyondexs.com/api/postempdeployment.php?',
    //  matProcurementUrl:'https://ppb.beyondexs.com/api/MaterialProcurementChart.php',
    //  stockorderUrl:'https://ppb.beyondexs.com/api/MaterialOrderReportController.php',
    //  alterNateMaterial:'https://ppb.beyondexs.com/api/AlterMaterialController.php',
  };

export const getUrlSlice = createSlice({
  name: "globalurl",
  initialState,
  reducers: {},
});

export default getUrlSlice.reducer;
